include classpath("application.conf")

node-address {
  protocol = http
  host = localhost
  port = 9324
  context-path = ""
}

rest-sqs {
  enabled = true
  bind-port = 9324
  bind-hostname = "0.0.0.0"
  sqs-limits = strict
}

queues {
  runs {
    defaultVisibilityTimeout = 60
    delay = 0
    receiveMessageWait = 20
    deadLettersQueue {
      name = "runs-dlq"
      maxReceiveCount = 3
    }
  }
  runs-dlq {
    defaultVisibilityTimeout = 60
    delay = 0
    receiveMessageWait = 0
  }
}
