/**
 * Event types — generated from the server's closed EventKind enum.
 * NEVER hand-maintain these; they are generated by scripts/generate-types.mjs.
 *
 * A new kind is a schema change with a migration, not a free-form string.
 */

export type EventKind =
  | "token"
  | "thought"
  | "tool_call"
  | "tool_result"
  | "step_start"
  | "step_end"
  | "checkpoint"
  | "error"
  | "done"
  | "cancelled";

export interface BaseEvent {
  run_id: string;
  seq: number;
  kind: EventKind;
  data: Record<string, unknown>;
  created_at: string;
}

export interface TokenEvent extends BaseEvent {
  kind: "token";
  data: {
    step_id: string;
    content: string;
    index: number;
  };
}

export interface ThoughtEvent extends BaseEvent {
  kind: "thought";
  data: {
    step_id: string;
    content: string;
  };
}

export interface ToolCallEvent extends BaseEvent {
  kind: "tool_call";
  data: {
    step_id: string;
    tool_name: string;
    arguments: Record<string, unknown>;
    call_id: string;
  };
}

export interface ToolResultEvent extends BaseEvent {
  kind: "tool_result";
  data: {
    step_id: string;
    call_id: string;
    result: unknown;
  };
}

export interface StepStartEvent extends BaseEvent {
  kind: "step_start";
  data: {
    step_id: string;
    attempt: number;
  };
}

export interface StepEndEvent extends BaseEvent {
  kind: "step_end";
  data: {
    step_id: string;
    state: string;
    output?: Record<string, unknown> | null;
    error?: Record<string, unknown> | null;
  };
}

export interface CheckpointEvent extends BaseEvent {
  kind: "checkpoint";
  data: {
    after_step: string;
    checkpoint_seq: number;
  };
}

export interface ErrorEvent extends BaseEvent {
  kind: "error";
  data: {
    step_id?: string | null;
    message: string;
    code?: string | null;
  };
}

export interface DoneEvent extends BaseEvent {
  kind: "done";
  data: {
    final_state: string;
    output?: Record<string, unknown> | null;
  };
}

export interface CancelledEvent extends BaseEvent {
  kind: "cancelled";
  data: {
    final_state: string;
  };
}

export type StreamEvent =
  | TokenEvent
  | ThoughtEvent
  | ToolCallEvent
  | ToolResultEvent
  | StepStartEvent
  | StepEndEvent
  | CheckpointEvent
  | ErrorEvent
  | DoneEvent
  | CancelledEvent;
